# Generated by Django 4.2.3 on 2023-11-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(default='Email', max_length=50),
        ),
    ]
