# Generated by Django 4.2.3 on 2023-10-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
