# Generated by Django 4.1.13 on 2023-12-15 07:04

import ckeditor_uploader.fields
import core.models
from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='res', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='No have', max_length=100)),
                ('username', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(upload_to=core.models.restaurant_directory_path)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('is_hot', models.BooleanField(default=False)),
                ('like', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
    ]
