# Generated by Django 4.2.3 on 2023-11-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantreview',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
    ]
