# Generated by Django 4.1.13 on 2023-12-15 07:04

import ckeditor_uploader.fields
import core.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('did', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=core.models.dish_directory_path)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is product', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=2, max_digits=30)),
                ('old_price', models.DecimalField(decimal_places=2, default=2, max_digits=30)),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In review'), ('published', 'Published')], default='not_paid_yet', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('digital', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.category')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='core.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
