# Generated by Django 4.1.13 on 2023-11-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurant_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='msg_receiver',
            new_name='msg_restaurant',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='msg_sender',
            new_name='msg_user',
        ),
    ]
