# Generated by Django 4.1.13 on 2023-12-15 07:05

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('number_seat', models.IntegerField(default=2)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
    ]
