# Generated by Django 4.1.13 on 2023-11-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_msg_receiver_chatmessage_msg_restaurant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
