# Generated by Django 4.2.3 on 2023-10-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ordercart_ordercartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercartitem',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='ordercartitem',
            name='ordercart',
        ),
        migrations.DeleteModel(
            name='OrderCart',
        ),
        migrations.DeleteModel(
            name='OrderCartItem',
        ),
    ]
