# Generated by Django 4.2.3 on 2023-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_restaurant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number_seat',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
