# Generated by Django 4.1.13 on 2023-12-15 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('ocid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('order_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('number_people', models.IntegerField(default=2)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ordercart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order Carts',
            },
        ),
        migrations.CreateModel(
            name='OrderCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish')),
                ('ordercart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordercart')),
            ],
            options={
                'verbose_name_plural': 'Order Carts Item',
            },
        ),
    ]
