# Generated by Django 4.2.3 on 2023-11-11 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ordercart_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='table',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='ordercart',
            name='time_to',
        ),
    ]
