# Generated by Django 4.2.3 on 2023-11-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_orderitem_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
