# Generated by Django 4.2.3 on 2023-11-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_order_date_ordercart_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercart',
            old_name='date',
            new_name='order_date',
        ),
    ]
