# Generated by Django 4.2.3 on 2023-11-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_date_ordercart_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number_seat',
            field=models.IntegerField(default=2),
        ),
    ]
