# Generated by Django 4.2.3 on 2023-11-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_table_number_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='order_date',
            field=models.DateField(),
        ),
    ]
