# Generated by Django 4.2.3 on 2023-11-12 04:06

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_order_date_alter_ordercart_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='oiid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_status',
            field=models.CharField(choices=[('awaiting_confirmation', 'Awaiting confirmation'), ('confirmed', 'Confirmed'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='awaiting_confirmation', max_length=50),
        ),
    ]
