# Generated by Django 4.2.3 on 2023-11-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_orderitem_oiid_alter_order_product_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
