# Generated by Django 4.2.3 on 2023-11-12 04:26

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oiid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', unique=True)),
                ('invoice_no', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=2, max_digits=50)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
